## Exploratory Data Analysis

In [ ]:
import pandas as pd

listings = pd.read_csv("data\\processed\\CRMLSListing.csv", low_memory=False)
sold = pd.read_csv("data\\processed\\CRMLSSold.csv", low_memory=False)

pd.set_option('display.max_rows', None)

Basics: Understanding the Structure

In [ ]:
print(f"Listing Size: {listings.shape}\n")
listings.head()

Listing Size: (1013413, 84)

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road

In [15]:
print(f"Sold Size: {sold.shape}\n")
sold.head()

Sold Size: (714371, 84)

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled,BuyerAgentAOR,ListAgentAOR,OriginatingSystemName,OriginatingSystemSubName
0,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,94401,6472.0,NaN,NaN,True,True,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,2024-01-24,950.0,...,92394,NaN,52320.0,NaN,False,False,NaN,NaN,NaN,NaN
2,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,2024-01-16,45000.0,...,93240,NaN,217364.0,NaN,False,False,NaN,NaN,NaN,NaN
3,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,2024-01-08,141500.0,...,92308,NaN,217800.0,NaN,False,False,NaN,NaN,NaN,NaN
4,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,2024-01-17,15000.0,...,93544,0.0,108883.0,NaN,False,False,NaN,NaN,NaN,NaN

Columns, Data Types, Missing Value Analysis

In [23]:
list_null = pd.DataFrame({
    'Dtype': listings.dtypes,
    'Null Count': listings.isnull().sum(),
    'Null Pct (%)': (listings.isnull().sum() / len(listings)) * 100
})

print("LISTINGS -------------------------------------------------------")
print(list_null)

sold_null = pd.DataFrame({
    'Dtype': sold.dtypes,
    'Null Count': sold.isnull().sum(),
    'Null Pct (%)': (sold.isnull().sum() / len(sold)) * 100
})

print("\nSOLD -----------------------------------------------------------")
print(sold_null)

LISTINGS -------------------------------------------------------
                                Dtype  Null Count  Null Pct (%)
OriginalListPrice             float64        3894      0.384246
ListingKey                      int64           0      0.000000
ListAgentEmail                 object      157404     15.532068
CloseDate                      object      675178     66.624170
ClosePrice                    float64      700346     69.107659
ListAgentFirstName             object        5787      0.571041
ListAgentLastName              object         126      0.012433
Latitude                      float64      114157     11.264608
Longitude                     float64      113354     11.185371
UnparsedAddress                object        2738      0.270176
PropertyType                   object           0      0.000000
LivingArea                    float64      124890     12.323702
ListPrice                     float64        2490      0.245704
DaysOnMarket                    int64           0      0.000000
ListOfficeName                 object           0      0.000000
BuyerOfficeName                object      686908     67.781645
CoListOfficeName               object      809536     79.882141
ListAgentFullName              object         322      0.031774
CoListAgentFirstName           object      810535     79.980719
CoListAgentLastName            object      809962     79.924177
BuyerAgentMlsId                object      685065     67.599784
BuyerAgentFirstName            object      685048     67.598107
BuyerAgentLastName             object      683946     67.489365
FireplacesTotal               float64     1013413    100.000000
AssociationFeeFrequency        object      720084     71.055335
AboveGradeFinishedArea        float64     1013413    100.000000
ListingKeyNumeric               int64           0      0.000000
MLSAreaMajor                   object      115246     11.372066
TaxAnnualAmount               float64     1006202     99.288444
CountyOrParish                 object           1      0.000099
PropertyType.1                 object           0      0.000000
MlsStatus                      object           0      0.000000
ElementarySchool               object      918357     90.620211
ListAgentFirstName.1           object        5787      0.571041
AttachedGarageYN               object      343435     33.888948
ParkingTotal                  float64       61303      6.049163
BuilderName                    object      979026     96.606813
PropertySubType                object      121649     12.003892
LotSizeAcres                  float64       94836      9.358080
SubdivisionName                object      673746     66.482865
BuyerOfficeAOR                 object      705045     69.571340
YearBuilt                     float64       81182      8.010752
DaysOnMarket.1                  int64           0      0.000000
BuyerAgencyCompensationType    object      889875     87.809708
StreetNumberNumeric           float64        4624      0.456280
LivingArea.1                  float64      124890     12.323702
ListingId                      object           0      0.000000
BathroomsTotalInteger         float64       82103      8.101633
City                           object        1009      0.099565
BuyerAgencyCompensation       float64      889894     87.811583
TaxYear                       float64     1012378     99.897870
BuildingAreaTotal             float64      852679     84.139339
BedroomsTotal                 float64      120858     11.925839
ContractStatusChangeDate       object        7707      0.760499
Longitude.1                   float64      113354     11.185371
ElementarySchoolDistrict      float64     1013413    100.000000
CoBuyerAgentFirstName          object      986729     97.366918
PurchaseContractDate           object      551605     54.430425
ListingContractDate            object           0      0.000000
BelowGradeFinishedArea        float64     1009142     99.578553
BusinessType                   object     1006446     99.312521
Latitude.1                    float64      114157     11.264608
ListPrice.1                   float64        2490      0.245704
StateOrProvince                object          87      0.008585
CoveredSpaces                 float64     1013413    100.000000
MiddleOrJuniorSchool           object      918326     90.617152
FireplaceYN                    object      143612     14.171123
Stories                       float64      259211     25.578022
HighSchool                     object      888373     87.661496
Levels                         object      191281     18.874931
ListAgentLastName.1            object         126      0.012433
CloseDate.1                    object      675178     66.624170
LotSizeDimensions              object      955814     94.316335
LotSizeArea                   float64       90491      8.929331
MainLevelBedrooms             float64      539286     53.214829
NewConstructionYN              object      135961     13.416149
GarageSpaces                  float64      189340     18.683400
HighSchoolDistrict             object      399317     39.403185
PostalCode                     object         259      0.025557
BuyerOfficeName.1              object      686908     67.781645
AssociationFee                float64      325397     32.109022
LotSizeSquareFeet             float64       91769      9.055439
MiddleOrJuniorSchoolDistrict  float64     1013413    100.000000
UnparsedAddress.1              object        2738      0.270176

SOLD -----------------------------------------------------------
                                Dtype  Null Count  Null Pct (%)
Flooring                       object      294496     41.224518
ViewYN                         object       71956     10.072637
WaterfrontYN                   object      713975     99.944567
BasementYN                     object      702598     98.351977
PoolPrivateYN                  object       87277     12.217321
OriginalListPrice             float64        2054      0.287526
ListingKey                      int64           0      0.000000
ListAgentEmail                 object      100176     14.022966
CloseDate                      object           0      0.000000
ClosePrice                    float64           8      0.001120
ListAgentFirstName             object        3958      0.554054
ListAgentLastName              object          66      0.009239
Latitude                      float64        6468      0.905412
Longitude                     float64        6318      0.884414
UnparsedAddress                object        1163      0.162801
PropertyType                   object           0      0.000000
LivingArea                    float64       49562      6.937852
ListPrice                     float64        1076      0.150622
DaysOnMarket                    int64           0      0.000000
ListOfficeName                 object           0      0.000000
BuyerOfficeName                object        8424      1.179219
CoListOfficeName               object      561367     78.581997
ListAgentFullName              object         215      0.030096
CoListAgentFirstName           object      566301     79.272675
CoListAgentLastName            object      565993     79.229560
BuyerAgentMlsId                object        2406      0.336800
BuyerAgentFirstName            object        2975      0.416450
BuyerAgentLastName             object         409      0.057253
FireplacesTotal               float64      714371    100.000000
AssociationFeeFrequency        object      502951     70.404734
AboveGradeFinishedArea        float64      714371    100.000000
ListingKeyNumeric               int64           0      0.000000
MLSAreaMajor                   object       79445     11.120972
TaxAnnualAmount               float64      711444     99.590269
CountyOrParish                 object           0      0.000000
MlsStatus                      object           0      0.000000
ElementarySchool               object      635572     88.969457
AttachedGarageYN               object      198523     27.789902
ParkingTotal                  float64       21822      3.054715
BuilderName                    object      687347     96.217092
PropertySubType                object       53782      7.528581
LotSizeAcres                  float64       66228      9.270813
SubdivisionName                object      461173     64.556512
BuyerOfficeAOR                 object       36275      5.077894
YearBuilt                     float64       29524      4.132867
BuyerAgencyCompensationType    object      628694     88.006652
StreetNumberNumeric           float64        1815      0.254070
ListingId                      object           0      0.000000
BathroomsTotalInteger         float64       32315      4.523560
City                           object         455      0.063692
BuyerAgencyCompensation       float64      628649     88.000353
TaxYear                       float64      713936     99.939107
BuildingAreaTotal             float64      621508     87.000732
BedroomsTotal                 float64       46655      6.530920
ContractStatusChangeDate       object         717      0.100368
ElementarySchoolDistrict      float64      714371    100.000000
CoBuyerAgentFirstName          object      655685     91.784941
PurchaseContractDate           object       14441      2.021499
ListingContractDate            object          86      0.012039
BelowGradeFinishedArea        float64      711097     99.541695
BusinessType                   object      712452     99.731372
StateOrProvince                object           2      0.000280
CoveredSpaces                 float64      714371    100.000000
MiddleOrJuniorSchool           object      634999     88.889247
FireplaceYN                    object       61483      8.606592
Stories                       float64      140379     19.650714
HighSchool                     object      610970     85.525588
Levels                         object       95375     13.350906
LotSizeDimensions              object      676603     94.713111
LotSizeArea                   float64       63958      8.953051
MainLevelBedrooms             float64      334231     46.786754
NewConstructionYN              object       84849     11.877442
GarageSpaces                  float64       91046     12.744918
HighSchoolDistrict             object      239225     33.487502
PostalCode                     object         204      0.028557
AssociationFee                float64      221327     30.982081
LotSizeSquareFeet             float64       64487      9.027102
MiddleOrJuniorSchoolDistrict  float64      714371    100.000000
latfilled                      object      552704     77.369322
lonfilled                      object      552704     77.369322
BuyerAgentAOR                  object       99775     13.966832
ListAgentAOR                   object       86034     12.043322
OriginatingSystemName          object      549064     76.859783
OriginatingSystemSubName       object      549064     76.859783

In [27]:
print("Null Percentages over 90% in Listings:")
print(list_null[list_null["Null Pct (%)"] > 90])
print("\nNull Percentages over 90% in Sold:")
print(sold_null[sold_null["Null Pct (%)"] > 90])

Null Percentages over 90% in Listings:
                                Dtype  Null Count  Null Pct (%)
FireplacesTotal               float64     1013413    100.000000
AboveGradeFinishedArea        float64     1013413    100.000000
TaxAnnualAmount               float64     1006202     99.288444
ElementarySchool               object      918357     90.620211
BuilderName                    object      979026     96.606813
TaxYear                       float64     1012378     99.897870
ElementarySchoolDistrict      float64     1013413    100.000000
CoBuyerAgentFirstName          object      986729     97.366918
BelowGradeFinishedArea        float64     1009142     99.578553
BusinessType                   object     1006446     99.312521
CoveredSpaces                 float64     1013413    100.000000
MiddleOrJuniorSchool           object      918326     90.617152
LotSizeDimensions              object      955814     94.316335
MiddleOrJuniorSchoolDistrict  float64     1013413    100.000000

Null Percentages over 90% in Sold:
                                Dtype  Null Count  Null Pct (%)
WaterfrontYN                   object      713975     99.944567
BasementYN                     object      702598     98.351977
FireplacesTotal               float64      714371    100.000000
AboveGradeFinishedArea        float64      714371    100.000000
TaxAnnualAmount               float64      711444     99.590269
BuilderName                    object      687347     96.217092
TaxYear                       float64      713936     99.939107
ElementarySchoolDistrict      float64      714371    100.000000
CoBuyerAgentFirstName          object      655685     91.784941
BelowGradeFinishedArea        float64      711097     99.541695
BusinessType                   object      712452     99.731372
CoveredSpaces                 float64      714371    100.000000
LotSizeDimensions              object      676603     94.713111
MiddleOrJuniorSchoolDistrict  float64      714371    100.000000